version = 0.1

[default.deploy.parameters]
stack_name = "spitz-news-mikke"
resolve_s3 = true
s3_prefix = "spitz-news-mikke"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "NotificationEmail=\"your-email@example.com\""
image_repositories = []

[default.global.parameters]
region = "ap-northeast-1"
